=== UniTime/unitime/JavaSource/menu.dtd
<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->
 
<!ELEMENT unitime-menu (menu|item|separator|remove)* >
 
<!ELEMENT menu ((parameter)*, (condition|new-condition)?,  (menu|item|separator|remove)*) >
<!ATTLIST menu name CDATA #REQUIRED >
<!ATTLIST menu title CDATA #IMPLIED >
<!ATTLIST menu page CDATA #IMPLIED >
<!ATTLIST menu type (gwt|property) #IMPLIED >
<!ATTLIST menu target (download|dialog|eval|tab) #IMPLIED >
<!ATTLIST menu hash CDATA #IMPLIED >
 
<!ELEMENT separator ((condition|new-condition)?) >

<!ELEMENT item ((parameter)*, (condition|new-condition)?) > 
<!ATTLIST item name CDATA #REQUIRED >
<!ATTLIST item page CDATA #REQUIRED >
<!ATTLIST item type (gwt|property|page) #IMPLIED >
<!ATTLIST item target (download|dialog|eval|tab) #IMPLIED >
<!ATTLIST item hash CDATA #IMPLIED >

<!ELEMENT condition (and|or|not|isAuthenticated|hasRole|hasProperty|propertyEquals|hasRight|hasPermission)* >

<!ELEMENT and (and|or|not|isAuthenticated|hasRole|hasProperty|propertyEquals|hasRight|hasPermission)* >
<!ELEMENT or (and|or|not|isAuthenticated|hasRole|hasProperty|propertyEquals|hasRight|hasPermission)* >
<!ELEMENT not (and|or|not|isAuthenticated|hasRole|hasProperty|propertyEquals|hasRight|hasPermission)* >
 
 <!ELEMENT isAuthenticated EMPTY >
 
<!ELEMENT hasRole EMPTY >
<!ATTLIST hasRole name CDATA #IMPLIED >

<!ELEMENT hasProperty EMPTY >
<!ATTLIST hasProperty name CDATA #REQUIRED >

<!ELEMENT propertyEquals EMPTY >
<!ATTLIST propertyEquals name CDATA #REQUIRED >
<!ATTLIST propertyEquals value CDATA #REQUIRED >
<!ATTLIST propertyEquals defaultValue CDATA #IMPLIED >

<!ELEMENT hasRight EMPTY >
<!ATTLIST hasRight name (canSeeCourses|canSeeTimetable|hasASolverGroup|canDoTimetable|canAudit|canSectionStudents|isSectioningEnabled|isRegistrationEnabled|canSeeEvents|isChameleon|hasPersonalReport|isStudent|hasRoomAvailability|canSeeExams|canTimetableExams|hasCourseReports|hasExamReports|hasStudentReports|hasEventReports|isInstructor|hasPointInTimeDataReports) #REQUIRED >

<!ELEMENT parameter (#PCDATA) >
<!ATTLIST parameter name CDATA #REQUIRED >
<!ATTLIST parameter value CDATA #IMPLIED >

<!ELEMENT hasPermission EMPTY >
<!ATTLIST hasPermission name CDATA #REQUIRED >
<!ATTLIST hasPermission authority (current|session|role|any) #IMPLIED >
<!ATTLIST hasPermission check (true|false) #IMPLIED >

<!-- custom menu -->
<!ATTLIST item position CDATA #IMPLIED >

<!ELEMENT remove EMPTY > 
<!ATTLIST remove name CDATA #REQUIRED >

<!ELEMENT new-condition (and|or|not|isAuthenticated|hasRole|hasProperty|propertyEquals|hasRight|hasPermission)* >

=== UniTime/unitime/JavaSource/menu-custom.xml
<?xml version="1.0"?>
<!DOCTYPE unitime-menu PUBLIC "-//UniTime//UniTime Menu DTD/EN" "http://www.unitime.org/interface/menu.dtd">
<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->
 <unitime-menu>
	<!-- Add custom administration menu with users -->
	<menu name="Administration">
		<menu name="Other">
			<item name="Users" page="admin" position="5" type="gwt">
				<parameter name="type">user</parameter>
				<!-- Only when LDAP is not configured -->
				<condition>
					<propertyEquals name="tmtbl.authenticate.ldap.provider" value="" defaultValue=""/>
					<hasPermission name="Users"/>
				</condition>
			</item>
		</menu>
	</menu>
	
	<!-- Example 1: no student sectioning -->
	<!-- 
	<remove name="Students"/>
	-->
	
	<!-- Example 2: no designator list -->
	<!-- 
	<menu name="Courses">
		<menu name="Input Data">
			<menu name="Instructors">
				<remove name="Designator List"/>
			</menu>
		</menu>
	</menu>
	-->
	
	<!-- Exampe 3: only administrator can see student sectioning -->
	<!-- 
	<menu name="Students">
		<new-condition>
			<hasRole name="Administrator"/>
		</new-condition>
	</menu>
	-->
	
	<!-- Example 4: show the old sectioning demo instead of the scheduling assistant (as a new item) -->
	<!-- 
	<menu name="Students">
		<remove name="Scheduling Assistant"/>
		<item name="Scheduling Demo" page="sectioningDemo.do" position="3"/>
	</menu>
	-->

	<!-- Example 5: show the old sectioning demo instead of the scheduling assistant (change the existing item) -->
	<!-- 
	<menu name="Students">
		<item name="Scheduling Assistant" page="sectioningDemo.do" type="page"/>
	</menu>
	-->
</unitime-menu>
